/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorShipments/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorShipments/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForRetailProcurementShipments);
  }
}(this, function(expect, SellingPartnerApiForRetailProcurementShipments) {
  'use strict';

  var instance;

  describe('vendorShipments', function() {
    describe('ShipmentInformation', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentInformation();
      });

      it('should create an instance of ShipmentInformation', function() {
        // TODO: update the code to test ShipmentInformation
        expect(instance).to.be.a(SellingPartnerApiForRetailProcurementShipments.ShipmentInformation);
      });

      it('should have the property vendorDetails (base name: "vendorDetails")', function() {
        // TODO: update the code to test the property vendorDetails
        expect(instance).to.have.property('vendorDetails');
        // expect(instance.vendorDetails).to.be(expectedValueLiteral);
      });

      it('should have the property buyerReferenceNumber (base name: "buyerReferenceNumber")', function() {
        // TODO: update the code to test the property buyerReferenceNumber
        expect(instance).to.have.property('buyerReferenceNumber');
        // expect(instance.buyerReferenceNumber).to.be(expectedValueLiteral);
      });

      it('should have the property shipToParty (base name: "shipToParty")', function() {
        // TODO: update the code to test the property shipToParty
        expect(instance).to.have.property('shipToParty');
        // expect(instance.shipToParty).to.be(expectedValueLiteral);
      });

      it('should have the property shipFromParty (base name: "shipFromParty")', function() {
        // TODO: update the code to test the property shipFromParty
        expect(instance).to.have.property('shipFromParty');
        // expect(instance.shipFromParty).to.be(expectedValueLiteral);
      });

      it('should have the property warehouseId (base name: "warehouseId")', function() {
        // TODO: update the code to test the property warehouseId
        expect(instance).to.have.property('warehouseId');
        // expect(instance.warehouseId).to.be(expectedValueLiteral);
      });

      it('should have the property masterTrackingId (base name: "masterTrackingId")', function() {
        // TODO: update the code to test the property masterTrackingId
        expect(instance).to.have.property('masterTrackingId');
        // expect(instance.masterTrackingId).to.be(expectedValueLiteral);
      });

      it('should have the property totalLabelCount (base name: "totalLabelCount")', function() {
        // TODO: update the code to test the property totalLabelCount
        expect(instance).to.have.property('totalLabelCount');
        // expect(instance.totalLabelCount).to.be(expectedValueLiteral);
      });

      it('should have the property shipMode (base name: "shipMode")', function() {
        // TODO: update the code to test the property shipMode
        expect(instance).to.have.property('shipMode');
        // expect(instance.shipMode).to.be(expectedValueLiteral);
      });

    });
  });

}));
