/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorShipments/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorShipments/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForRetailProcurementShipments);
  }
}(this, function(expect, SellingPartnerApiForRetailProcurementShipments) {
  'use strict';

  var instance;

  describe('vendorShipments', function() {
    describe('TotalWeight', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForRetailProcurementShipments.TotalWeight();
      });

      it('should create an instance of TotalWeight', function() {
        // TODO: update the code to test TotalWeight
        expect(instance).to.be.a(SellingPartnerApiForRetailProcurementShipments.TotalWeight);
      });

      it('should have the property unitOfMeasure (base name: "unitOfMeasure")', function() {
        // TODO: update the code to test the property unitOfMeasure
        expect(instance).to.have.property('unitOfMeasure');
        // expect(instance.unitOfMeasure).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

    });
  });

}));
