/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/sellers/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/sellers/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheSellingPartnerApiForSellers);
  }
}(this, function(expect, TheSellingPartnerApiForSellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheSellingPartnerApiForSellers.SellersApi();
  });

  describe('sellers', function() {
    describe('SellersApi', function() {
      describe('getAccount', function() {
        it('should call getAccount successfully', function(done) {
          // TODO: uncomment getAccount call and complete the assertions
          /*

          instance.getAccount().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(TheSellingPartnerApiForSellers.GetAccountResponse);
            expect(data.payload).to.be.a(TheSellingPartnerApiForSellers.Account);
                  expect(data.payload.marketplaceParticipationList).to.be.a(TheSellingPartnerApiForSellers.MarketplaceParticipationList);
                  expect(data.payload.businessType).to.be.a('string');
              // expect(data.payload.businessType).to.be("CHARITY");
              expect(data.payload.sellingPlan).to.be.a('string');
              // expect(data.payload.sellingPlan).to.be("PROFESSIONAL");
              expect(data.payload.business).to.be.a(TheSellingPartnerApiForSellers.Business);
                    expect(data.payload.business.name).to.be.a('string');
                // expect(data.payload.business.name).to.be("");
                expect(data.payload.business.registeredBusinessAddress).to.be.a(TheSellingPartnerApiForSellers.Address);
                      expect(data.payload.business.registeredBusinessAddress.addressLine1).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.addressLine1).to.be("");
                  expect(data.payload.business.registeredBusinessAddress.addressLine2).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.addressLine2).to.be("");
                  expect(data.payload.business.registeredBusinessAddress.countryCode).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.countryCode).to.be("");
                  expect(data.payload.business.registeredBusinessAddress.stateOrProvinceCode).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.stateOrProvinceCode).to.be("");
                  expect(data.payload.business.registeredBusinessAddress.city).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.city).to.be("");
                  expect(data.payload.business.registeredBusinessAddress.postalCode).to.be.a('string');
                  // expect(data.payload.business.registeredBusinessAddress.postalCode).to.be("");
                expect(data.payload.business.companyRegistrationNumber).to.be.a('string');
                // expect(data.payload.business.companyRegistrationNumber).to.be("");
                expect(data.payload.business.companyTaxIdentificationNumber).to.be.a('string');
                // expect(data.payload.business.companyTaxIdentificationNumber).to.be("");
                expect(data.payload.business.nonLatinName).to.be.a('string');
                // expect(data.payload.business.nonLatinName).to.be("");
              expect(data.payload.primaryContact).to.be.a(TheSellingPartnerApiForSellers.PrimaryContact);
                    expect(data.payload.primaryContact.name).to.be.a('string');
                // expect(data.payload.primaryContact.name).to.be("");
                expect(data.payload.primaryContact.address).to.be.a(TheSellingPartnerApiForSellers.Address);
                      expect(data.payload.primaryContact.address.addressLine1).to.be.a('string');
                  // expect(data.payload.primaryContact.address.addressLine1).to.be("");
                  expect(data.payload.primaryContact.address.addressLine2).to.be.a('string');
                  // expect(data.payload.primaryContact.address.addressLine2).to.be("");
                  expect(data.payload.primaryContact.address.countryCode).to.be.a('string');
                  // expect(data.payload.primaryContact.address.countryCode).to.be("");
                  expect(data.payload.primaryContact.address.stateOrProvinceCode).to.be.a('string');
                  // expect(data.payload.primaryContact.address.stateOrProvinceCode).to.be("");
                  expect(data.payload.primaryContact.address.city).to.be.a('string');
                  // expect(data.payload.primaryContact.address.city).to.be("");
                  expect(data.payload.primaryContact.address.postalCode).to.be.a('string');
                  // expect(data.payload.primaryContact.address.postalCode).to.be("");
                expect(data.payload.primaryContact.nonLatinName).to.be.a('string');
                // expect(data.payload.primaryContact.nonLatinName).to.be("");
            expect(data.errors).to.be.a(TheSellingPartnerApiForSellers.ErrorList);
    
            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMarketplaceParticipations', function() {
        it('should call getMarketplaceParticipations successfully', function(done) {
          // TODO: uncomment getMarketplaceParticipations call and complete the assertions
          /*

          instance.getMarketplaceParticipations().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(TheSellingPartnerApiForSellers.GetMarketplaceParticipationsResponse);
            expect(data.payload).to.be.a(TheSellingPartnerApiForSellers.MarketplaceParticipationList);
                expect(data.errors).to.be.a(TheSellingPartnerApiForSellers.ErrorList);
    
            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
