/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {MarketplaceParticipation} from './MarketplaceParticipation.js';

/**
 * The MarketplaceParticipationList model module.
 * @module sellers/js-client.sellers.model/MarketplaceParticipationList
 * @version v1
 */
export class MarketplaceParticipationList extends Array {
  /**
   * Constructs a new <code>MarketplaceParticipationList</code>.
   * List of marketplace participations.
   * @alias module:sellers/js-client.sellers.model/MarketplaceParticipationList
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>MarketplaceParticipationList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellers/js-client.sellers.model/MarketplaceParticipationList} obj Optional instance to populate.
   * @return {module:sellers/js-client.sellers.model/MarketplaceParticipationList} The populated <code>MarketplaceParticipationList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new MarketplaceParticipationList();
      ApiClient.constructFromObject(data, obj, 'MarketplaceParticipation');
    }
    return obj;
  }
}

