/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The Participation model module.
 * @module sellers/js-client.sellers.model/Participation
 * @version v1
 */
export class Participation {
  /**
   * Constructs a new <code>Participation</code>.
   * Detailed information that is specific to a seller in a marketplace.
   * @alias module:sellers/js-client.sellers.model/Participation
   * @class
   * @param isParticipating {Boolean} If true, the seller participates in the marketplace.
   * @param hasSuspendedListings {Boolean} If true, the seller has suspended listings.
   */
  constructor(isParticipating, hasSuspendedListings) {
    this.isParticipating = isParticipating;
    this.hasSuspendedListings = hasSuspendedListings;
  }

  /**
   * Constructs a <code>Participation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellers/js-client.sellers.model/Participation} obj Optional instance to populate.
   * @return {module:sellers/js-client.sellers.model/Participation} The populated <code>Participation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new Participation();
      if (data.hasOwnProperty('isParticipating'))
        obj.isParticipating = ApiClient.convertToType(data['isParticipating'], 'Boolean');
      if (data.hasOwnProperty('hasSuspendedListings'))
        obj.hasSuspendedListings = ApiClient.convertToType(data['hasSuspendedListings'], 'Boolean');
    }
    return obj;
  }
}

/**
 * If true, the seller participates in the marketplace.
 * @member {Boolean} isParticipating
 */
Participation.prototype.isParticipating = undefined;

/**
 * If true, the seller has suspended listings.
 * @member {Boolean} hasSuspendedListings
 */
Participation.prototype.hasSuspendedListings = undefined;


