/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Address} from './Address.js';

/**
 * The PrimaryContact model module.
 * @module sellers/js-client.sellers.model/PrimaryContact
 * @version v1
 */
export class PrimaryContact {
  /**
   * Constructs a new <code>PrimaryContact</code>.
   * Information about the seller's primary contact.
   * @alias module:sellers/js-client.sellers.model/PrimaryContact
   * @class
   * @param name {String} The full name of the seller's primary contact.
   * @param address {module:sellers/js-client.sellers.model/Address} The primary contact's residential address.
   */
  constructor(name, address) {
    this.name = name;
    this.address = address;
  }

  /**
   * Constructs a <code>PrimaryContact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellers/js-client.sellers.model/PrimaryContact} obj Optional instance to populate.
   * @return {module:sellers/js-client.sellers.model/PrimaryContact} The populated <code>PrimaryContact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new PrimaryContact();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = Address.constructFromObject(data['address']);
      if (data.hasOwnProperty('nonLatinName'))
        obj.nonLatinName = ApiClient.convertToType(data['nonLatinName'], 'String');
    }
    return obj;
  }
}

/**
 * The full name of the seller's primary contact.
 * @member {String} name
 */
PrimaryContact.prototype.name = undefined;

/**
 * The primary contact's residential address.
 * @member {module:sellers/js-client.sellers.model/Address} address
 */
PrimaryContact.prototype.address = undefined;

/**
 * The non-Latin script version of the primary contact's name, if applicable.
 * @member {String} nonLatinName
 */
PrimaryContact.prototype.nonLatinName = undefined;


