/*
 * Selling Partner API for Direct Fulfillment Shipping
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: 2021-12-28
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorDirectFulfillmentShipping_2021-12-28/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorDirectFulfillmentShipping_2021-12-28/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForDirectFulfillmentShipping);
  }
}(this, function(expect, SellingPartnerApiForDirectFulfillmentShipping) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForDirectFulfillmentShipping.CreateContainerLabelApi();
  });

  describe('vendorDirectFulfillmentShipping_2021-12-28', function() {
    describe('CreateContainerLabelApi', function() {
      describe('createContainerLabel', function() {
        it('should call createContainerLabel successfully', function(done) {
          // TODO: uncomment, update parameter values for createContainerLabel call and complete the assertions
          /*
          var body = new SellingPartnerApiForDirectFulfillmentShipping.CreateContainerLabelRequest();
          body.sellingParty = new SellingPartnerApiForDirectFulfillmentShipping.PartyIdentification();
          body.sellingParty.partyId = "";
          body.sellingParty.address = new SellingPartnerApiForDirectFulfillmentShipping.Address();
          body.sellingParty.address.name = "";
          body.sellingParty.address.addressLine1 = "";
          body.sellingParty.address.addressLine2 = "";
          body.sellingParty.address.addressLine3 = "";
          body.sellingParty.address.city = "";
          body.sellingParty.address.county = "";
          body.sellingParty.address.district = "";
          body.sellingParty.address.stateOrRegion = "";
          body.sellingParty.address.postalCode = "";
          body.sellingParty.address.countryCode = "";
          body.sellingParty.address.phone = "";
          body.sellingParty.taxRegistrationDetails = [new SellingPartnerApiForDirectFulfillmentShipping.TaxRegistrationDetails()];
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress = new SellingPartnerApiForDirectFulfillmentShipping.Address();
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.name = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine1 = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine2 = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine3 = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.city = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.county = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.district = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.stateOrRegion = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.postalCode = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.countryCode = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationAddress.phone = "";
          body.sellingParty.taxRegistrationDetails[0].taxRegistrationMessages = "";
          body.shipFromParty = new SellingPartnerApiForDirectFulfillmentShipping.PartyIdentification();
          body.shipFromParty.partyId = "";
          body.shipFromParty.address = new SellingPartnerApiForDirectFulfillmentShipping.Address();
          body.shipFromParty.address.name = "";
          body.shipFromParty.address.addressLine1 = "";
          body.shipFromParty.address.addressLine2 = "";
          body.shipFromParty.address.addressLine3 = "";
          body.shipFromParty.address.city = "";
          body.shipFromParty.address.county = "";
          body.shipFromParty.address.district = "";
          body.shipFromParty.address.stateOrRegion = "";
          body.shipFromParty.address.postalCode = "";
          body.shipFromParty.address.countryCode = "";
          body.shipFromParty.address.phone = "";
          body.shipFromParty.taxRegistrationDetails = [new SellingPartnerApiForDirectFulfillmentShipping.TaxRegistrationDetails()];
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress = new SellingPartnerApiForDirectFulfillmentShipping.Address();
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.name = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine1 = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine2 = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.addressLine3 = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.city = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.county = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.district = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.stateOrRegion = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.postalCode = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.countryCode = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationAddress.phone = "";
          body.shipFromParty.taxRegistrationDetails[0].taxRegistrationMessages = "";
          body.carrierId = new SellingPartnerApiForDirectFulfillmentShipping.CarrierId();
          body.vendorContainerId = new SellingPartnerApiForDirectFulfillmentShipping.VendorContainerId();
          body.packages = new SellingPartnerApiForDirectFulfillmentShipping.Packages();

          instance.createContainerLabel(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForDirectFulfillmentShipping.CreateContainerLabelResponse);
            expect(data.containerLabel).to.be.a(SellingPartnerApiForDirectFulfillmentShipping.ContainerLabel);
                  expect(data.containerLabel.containerTrackingNumber).to.be.a('string');
              // expect(data.containerLabel.containerTrackingNumber).to.be("");
              expect(data.containerLabel.content).to.be.a('string');
              // expect(data.containerLabel.content).to.be("");
              expect(data.containerLabel.format).to.be.a(SellingPartnerApiForDirectFulfillmentShipping.ContainerLabelFormat);
      

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
