/*
 * The Selling Partner API for Sellers
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/sellers/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/sellers/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheSellingPartnerApiForSellers);
  }
}(this, function(expect, TheSellingPartnerApiForSellers) {
  'use strict';

  var instance;

  describe('sellers', function() {
    describe('Participation', function() {
      beforeEach(function() {
        instance = new TheSellingPartnerApiForSellers.Participation();
      });

      it('should create an instance of Participation', function() {
        // TODO: update the code to test Participation
        expect(instance).to.be.a(TheSellingPartnerApiForSellers.Participation);
      });

      it('should have the property isParticipating (base name: "isParticipating")', function() {
        // TODO: update the code to test the property isParticipating
        expect(instance).to.have.property('isParticipating');
        // expect(instance.isParticipating).to.be(expectedValueLiteral);
      });

      it('should have the property hasSuspendedListings (base name: "hasSuspendedListings")', function() {
        // TODO: update the code to test the property hasSuspendedListings
        expect(instance).to.have.property('hasSuspendedListings');
        // expect(instance.hasSuspendedListings).to.be(expectedValueLiteral);
      });

    });
  });

}));
