/*
 * Vendor Invoices v1
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorInvoices/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorInvoices/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VendorInvoicesV1);
  }
}(this, function(expect, VendorInvoicesV1) {
  'use strict';

  var instance;

  describe('vendorInvoices', function() {
    describe('NetCostUnitOfMeasure', function() {
      beforeEach(function() {
        instance = VendorInvoicesV1.NetCostUnitOfMeasure;
      });

      it('should create an instance of NetCostUnitOfMeasure', function() {
        // TODO: update the code to test NetCostUnitOfMeasure
        expect(instance).to.be.a('object');
      });

      it('should have the property POUNDS', function() {
        expect(instance).to.have.property('POUNDS');
        expect(instance.POUNDS).to.be("POUNDS");
      });

      it('should have the property OUNCES', function() {
        expect(instance).to.have.property('OUNCES');
        expect(instance.OUNCES).to.be("OUNCES");
      });

      it('should have the property GRAMS', function() {
        expect(instance).to.have.property('GRAMS');
        expect(instance.GRAMS).to.be("GRAMS");
      });

      it('should have the property KILOGRAMS', function() {
        expect(instance).to.have.property('KILOGRAMS');
        expect(instance.KILOGRAMS).to.be("KILOGRAMS");
      });

    });
  });

}));
