/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * OpenAPI spec version: 2024-05-09
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/awd_2024-05-09/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/awd_2024-05-09/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheSellingPartnerApiForAmazonWarehousingAndDistribution);
  }
}(this, function(expect, TheSellingPartnerApiForAmazonWarehousingAndDistribution) {
  'use strict';

  var instance;

  describe('awd_2024-05-09', function() {
    describe('PrepDetails', function() {
      beforeEach(function() {
        instance = new TheSellingPartnerApiForAmazonWarehousingAndDistribution.PrepDetails();
      });

      it('should create an instance of PrepDetails', function() {
        // TODO: update the code to test PrepDetails
        expect(instance).to.be.a(TheSellingPartnerApiForAmazonWarehousingAndDistribution.PrepDetails);
      });

      it('should have the property labelOwner (base name: "labelOwner")', function() {
        // TODO: update the code to test the property labelOwner
        expect(instance).to.have.property('labelOwner');
        // expect(instance.labelOwner).to.be(expectedValueLiteral);
      });

      it('should have the property prepCategory (base name: "prepCategory")', function() {
        // TODO: update the code to test the property prepCategory
        expect(instance).to.have.property('prepCategory');
        // expect(instance.prepCategory).to.be(expectedValueLiteral);
      });

      it('should have the property prepInstructions (base name: "prepInstructions")', function() {
        // TODO: update the code to test the property prepInstructions
        expect(instance).to.have.property('prepInstructions');
        // expect(instance.prepInstructions).to.be(expectedValueLiteral);
      });

      it('should have the property prepOwner (base name: "prepOwner")', function() {
        // TODO: update the code to test the property prepOwner
        expect(instance).to.have.property('prepOwner');
        // expect(instance.prepOwner).to.be(expectedValueLiteral);
      });

    });
  });

}));
